global using System.ComponentModel;
global using System.Data;
global using System.IO;
global using System.Speech.Synthesis;
global using System.Text.Json;
global using System.Windows;
global using System.Windows.Data;
global using System.Windows.Input;
global using AlexPiApi.Services;
global using Azure.Identity;
global using Azure.Security.KeyVault.Secrets;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Db.OneBase.Model;
global using Microsoft.Extensions.Configuration;
global using static System.Diagnostics.Trace;
global using Application = System.Windows.Application;
global using System.Diagnostics;
